[package]
name = "vcd_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
cli-log = "2.1.0"
crossterm = "0.28.1"
ratatui = "0.29.0"
vcd = "0.7.0"
tui-textarea = "0.7.0"
catppuccin = { version = "2.5.1" , features = ["ratatui"]}
